stages:
  - run

run_docker:
  only:
    - master
  stage: run
  script:
    - echo "$SEQUELIZE_DATABASE"
    - docker build -t resumeapi .
    - docker ps --quiet --filter="name=resumeapi" | xargs --no-run-if-empty docker rm -f
    - docker run -d --network=host --restart always --name resumeapi resumeapi
  tags:
    - master-runner
