stages:
  - run

run_docker:
  only:
    - master
  stage: run
  script:
    - docker build -t resumeapi .
    - docker ps --quiet --filter="name=resumeapi" | xargs --no-run-if-empty docker rm -f
    - docker run -dt -p 9000:9000 --restart always --name resumeapi resumeapi
  tags:
    - master-runner
