# fly.toml file generated for resume-api on 2023-04-18T17:35:04+08:00

app = "resume-api"
primary_region = "nrt"

[http_service]
  internal_port = 9000
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
